# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='view_only_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
