# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0002_trip_view_only_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
